#pragma once

// .h autogenerated by cmake !

#define APPLE_SIERRA_OR_NEWER 0
#define USE_TCMALLOC 1
#define USE_JEMALLOC 0
#define USE_READLINE 1
#define USE_LIBEDIT 0
#define HAVE_READLINE_HISTORY 1
