#pragma once

// .h autogenerated by cmake!

#define USE_DBMS_TCP_PROTOCOL_VERSION 0

#if USE_DBMS_TCP_PROTOCOL_VERSION
    #include "Core/Defines.h"
    #ifndef VERSION_REVISION
        #define VERSION_REVISION DBMS_TCP_PROTOCOL_VERSION
    #endif
#else
    #define VERSION_REVISION 54310
#endif

#define VERSION_STRING "1.1.54310"
#define VERSION_FULL "ClickHouse 1.1.54310"
#define VERSION_DESCRIBE "v1.1.54310-testing"
