#pragma once

// .h autogenerated by cmake!

#define USE_ICU 1
#define USE_MYSQL 1
#define USE_RE2_ST 1
#define USE_VECTORCLASS 0
#define USE_RDKAFKA 1
#define USE_CAPNP 0
#define Poco_DataODBC_FOUND 1
#define Poco_MongoDB_FOUND 1
#define Poco_NetSSL_FOUND 1
