// .cpp autogenerated by cmake

#include <Common/config_build.h>

const char * auto_config_build[]
{
    "VERSION_FULL", "ClickHouse 1.1.54310",
    "VERSION_DESCRIBE", "v1.1.54310-testing",
    "BUILD_DATE", "2017-12-06",
    "BUILD_TYPE", "Release",
    "SYSTEM", "Linux-4.13.5-1-ARCH",
    "SYSTEM_PROCESSOR", "x86_64",
    "LIBRARY_ARCHITECTURE", "",
    "CMAKE_VERSION", "3.9.4",
    "C_COMPILER", "/usr/bin/cc",
    "C_COMPILER_VERSION", "7.2.0",
    "CXX_COMPILER", "/usr/bin/c++",
    "CXX_COMPILER_VERSION", "7.2.0",
    "C_FLAGS", "  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer -Wall  -O3 -DNDEBUG",
    "CXX_FLAGS", "  -D_GLIBCXX_USE_CXX11_ABI=1 -pipe -msse4.1 -msse4.2 -mpopcnt -std=gnu++1z  -fno-omit-frame-pointer -Wall -Wnon-virtual-dtor  -O3 -DNDEBUG",
    "LINK_FLAGS", " -static-libgcc -static-libstdc++  -D_GLIBCXX_USE_CXX11_ABI=1",
    "BUILD_COMPILE_DEFINITIONS", "",
    "BUILD_INCLUDE_DIRECTORIES", "/usr/include;/usr/include;/usr/include",
    "STATIC", "False",
    nullptr, nullptr
};
